name: flutter_tips
description: A Flutter application for macOS based on Vandad&#x27;s flutter-tips-and-tricks series
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  collection: ^1.16.0
  desktop_multi_window: ^0.0.2
  macos_ui: ^1.4.1+1
  path_provider: ^2.0.11  
  url_launcher: ^6.1.3
  rxdart: ^0.27.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  async: ^2.8.0
  dio: ^4.0.6
  logger: ^1.1.0
  tips_repository:
    path: packages/tips_repository      
  tips_and_tricks_api:
    path: packages/tips_and_tricks_api        
  cached_network_image: ^3.2.1
  flutter_platform_widgets: ^2.0.0
  flutter_spinkit: ^5.1.0
  tuple: ^2.0.0
  flutter_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  build_runner: ^2.1.10  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
