name: tips_and_tricks_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  path_provider: ^2.0.11
  logger: ^1.1.0

  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
